"""empty message

Revision ID: 1ceac92101e1
Revises: 836c528e24fc
Create Date: 2022-03-23 11:58:03.076010

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from project import models


# revision identifiers, used by Alembic.
revision = '1ceac92101e1'
down_revision = '836c528e24fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_manager_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'manager_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_manager_id_fkey', 'orders', 'user', ['manager_id'], ['id'])
    # ### end Alembic commands ###

