"""empty message

Revision ID: 29563cac3883
Revises: b5643aaca350
Create Date: 2022-03-21 11:39:00.885943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29563cac3883'
down_revision = 'b5643aaca350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor_code', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('composition', sa.String(length=255), nullable=False),
    sa.Column('net_weight', sa.Integer(), nullable=False),
    sa.Column('energy_value', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('main_picture', sa.String(length=255), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('status_product', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['status_product'], ['product_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
