"""empty message

Revision ID: 29b3340c91ba
Revises: b26843d8e978
Create Date: 2022-03-21 16:07:11.902193

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from project import models
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29b3340c91ba'
down_revision = 'b26843d8e978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor_code', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('composition', sa.String(length=255), nullable=True),
    sa.Column('net_weight', sa.Integer(), nullable=True),
    sa.Column('energy_value', sa.Integer(), nullable=True),
    sa.Column('expiration_date', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('main_picture', sa.String(length=255), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(models.Product.STATUS), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('vendor_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('composition', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('net_weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('energy_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expiration_date', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('main_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_product', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], name='product_category_fkey'),
    sa.ForeignKeyConstraint(['status_product'], ['product_status.id'], name='product_status_product_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_pkey')
    )
    op.drop_table('products')
    # ### end Alembic commands ###
