"""empty message

Revision ID: 4affecde35f9
Revises: 6dba2bf0ab52
Create Date: 2022-03-16 17:50:00.355976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4affecde35f9'
down_revision = '6dba2bf0ab52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
