"""empty message

Revision ID: 4b479f31b45c
Revises: 86c71fc7dec0
Create Date: 2022-03-23 10:37:01.248611

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from project import models


# revision identifiers, used by Alembic.
revision = '4b479f31b45c'
down_revision = '86c71fc7dec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('buy', sqlalchemy_utils.types.choice.ChoiceType(models.Order.BUY), nullable=True),
    sa.Column('delivery', sqlalchemy_utils.types.choice.ChoiceType(models.Order.DELIVERY), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(models.Order.STATUS), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###

