"""empty message

Revision ID: 4d63c2f9ad86
Revises: 1ceac92101e1
Create Date: 2022-03-23 12:32:09.495961

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from project import models


# revision identifiers, used by Alembic.
revision = '4d63c2f9ad86'
down_revision = '1ceac92101e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'user', ['user'], ['id'])
    op.create_foreign_key(None, 'orders', 'user', ['manager_id'], ['id'])
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'user', ['user_id'], ['id'])
    op.drop_column('orders', 'manager_id')
    op.drop_column('orders', 'user')
    # ### end Alembic commands ###

