"""empty message

Revision ID: 5c0453f3f5af
Revises: 5cf686209f71
Create Date: 2022-03-23 16:23:14.722077

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from project import models


# revision identifiers, used by Alembic.
revision = '5c0453f3f5af'
down_revision = '5cf686209f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.drop_constraint('orders_user_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_manager_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'user', ['manager_id'], ['id'])
    op.drop_column('orders', 'manager')
    op.drop_column('orders', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('manager', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_manager_fkey', 'orders', 'user', ['manager'], ['id'])
    op.create_foreign_key('orders_user_fkey', 'orders', 'user', ['user'], ['id'])
    op.drop_column('orders', 'manager_id')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###

