"""empty message

Revision ID: 5cf686209f71
Revises: 697f01b6a579
Create Date: 2022-03-23 16:22:25.078953

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from project import models


# revision identifiers, used by Alembic.
revision = '5cf686209f71'
down_revision = '697f01b6a579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'user')
    # ### end Alembic commands ###

