"""empty message

Revision ID: 697f01b6a579
Revises: ffd857eb30ee
Create Date: 2022-03-23 16:21:49.804115

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from project import models


# revision identifiers, used by Alembic.
revision = '697f01b6a579'
down_revision = 'ffd857eb30ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_user_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_user_fkey', 'orders', 'user', ['user'], ['id'])
    # ### end Alembic commands ###

