"""empty message

Revision ID: c67eba1e5eeb
Revises: d79507c265b8
Create Date: 2022-03-22 10:34:11.187687

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from project import models


# revision identifiers, used by Alembic.
revision = 'c67eba1e5eeb'
down_revision = 'd79507c265b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_category_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_category_fkey', 'products', 'category', ['category'], ['id'])
    # ### end Alembic commands ###

