"""empty message

Revision ID: d79507c265b8
Revises: 29b3340c91ba
Create Date: 2022-03-22 10:28:31.800546

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from project import models


# revision identifiers, used by Alembic.
revision = 'd79507c265b8'
down_revision = '29b3340c91ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

